name: flag_secure_example
description: "An example on how to use the flag_secure plugin."

repository: https://github.com/maelchiotti/flag_secure/example

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flag_secure:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
