name: flag_secure
description: "A Flutter plugin to manage Android's FLAG_SECURE at runtime."

repository: https://github.com/maelchiotti/flag_secure
issue_tracker: https://github.com/maelchiotti/flag_secure/issues

version: 2.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.maelchiotti.flag_secure.flag_secure
        pluginClass: FlagSecurePlugin
